# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-frontend-deployment
  namespace: mlops
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: mlops-frontend
  template:
    metadata:
      labels:
        app: mlops-frontend
    spec:
      containers:
      - name: mlops-frontend
        image: olawaleoyg/mlops:latest  # Replace with your DockerHub image
        ports:
        - containerPort: 3000
