apiVersion: v1
kind: Service
metadata:
  name: mlops-frontend-service
  namespace: mlops
spec:
  selector:
    app: mlops-frontend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  type: ClusterIP  # Use NodePort or ClusterIP based on your requirements

# localhost -> service-port -> target-port -> containerPort -> image-exposed-Port
# (5000)            (150)            (3000)          (3000)            (3000)
